TRACKS = [
    # Core programming
    ("Programming", "General Programming"),
    ("Python", "Programming Languages"),
    ("C", "Programming Languages"),
    ("C++", "Programming Languages"),
    ("C#", "Programming Languages"),
    ("Java", "Programming Languages"),
    ("JavaScript", "Programming Languages"),
    ("TypeScript", "Programming Languages"),
    ("Go", "Programming Languages"),
    ("Rust", "Programming Languages"),
    ("PHP", "Programming Languages"),
    ("Kotlin", "Programming Languages"),
    ("Swift", "Programming Languages"),

    # CS fundamentals
    ("Data Structures", "Computer Science Fundamentals"),
    ("Algorithms", "Computer Science Fundamentals"),
    ("Competitive Programming", "Computer Science Fundamentals"),
    ("Object-Oriented Programming", "Computer Science Fundamentals"),
    ("Software Engineering", "Software Engineering"),
    ("Design Patterns", "Software Engineering"),
    ("Clean Code", "Software Engineering"),
    ("Software Testing", "Software Engineering"),
    ("QA", "Software Engineering"),
    ("Git & GitHub", "Developer Tools"),

    # Web
    ("Frontend Development", "Web Development"),
    ("HTML & CSS", "Web Development"),
    ("React", "Web Development"),
    ("Angular", "Web Development"),
    ("Vue.js", "Web Development"),
    ("Backend Development", "Web Development"),
    ("Node.js", "Web Development"),
    ("Django", "Web Development"),
    ("Flask", "Web Development"),
    ("ASP.NET", "Web Development"),
    ("Full Stack Development", "Web Development"),

    # Mobile
    ("Flutter", "Mobile Development"),
    ("Android Development", "Mobile Development"),
    ("iOS Development", "Mobile Development"),
    ("React Native", "Mobile Development"),

    # Data
    ("SQL", "Data"),
    ("Databases", "Data"),
    ("Data Analysis", "Data"),
    ("Data Science", "Data"),
    ("Business Intelligence", "Data"),
    ("Data Engineering", "Data"),
    ("Big Data", "Data"),

    # AI
    ("Artificial Intelligence", "AI & ML"),
    ("Machine Learning", "AI & ML"),
    ("Deep Learning", "AI & ML"),
    ("Computer Vision", "AI & ML"),
    ("Natural Language Processing", "AI & ML"),
    ("Generative AI", "AI & ML"),
    ("Large Language Models", "AI & ML"),
    ("Reinforcement Learning", "AI & ML"),
    ("MLOps", "AI & ML"),

    # Cloud / DevOps / Systems
    ("Cloud Computing", "Cloud & Infrastructure"),
    ("AWS", "Cloud & Infrastructure"),
    ("Microsoft Azure", "Cloud & Infrastructure"),
    ("Google Cloud", "Cloud & Infrastructure"),
    ("DevOps", "Cloud & Infrastructure"),
    ("Docker", "Cloud & Infrastructure"),
    ("Kubernetes", "Cloud & Infrastructure"),
    ("Linux", "Systems"),
    ("Computer Networks", "Systems"),
    ("Operating Systems", "Systems"),
    ("System Administration", "Systems"),

    # Security
    ("Cybersecurity", "Cybersecurity"),
    ("Ethical Hacking", "Cybersecurity"),
    ("Web Security", "Cybersecurity"),
    ("Network Security", "Cybersecurity"),
    ("Digital Forensics", "Cybersecurity"),

    # Other technology
    ("Embedded Systems", "Embedded & Hardware"),
    ("Internet of Things", "Embedded & Hardware"),
    ("Robotics", "Embedded & Hardware"),
    ("Game Development", "Game Development"),
    ("Unity", "Game Development"),
    ("Unreal Engine", "Game Development"),
    ("Blockchain", "Emerging Technology"),
    ("Web3", "Emerging Technology"),
    ("AR VR", "Emerging Technology"),
    ("UI UX", "Design & Product"),
    ("Product Management", "Design & Product"),
]

TRACK_ALIAS = {
    "Microsoft Azure": "Azure",
    "Google Cloud": "GCP Google Cloud",
    "Artificial Intelligence": "AI",
    "Machine Learning": "Machine Learning",
    "Deep Learning": "Deep Learning",
    "Natural Language Processing": "NLP",
    "Large Language Models": "LLM",
    "Internet of Things": "IoT",
    "AR VR": "AR VR",
    "UI UX": "UI UX",
}

# Multiple natural-language queries per track improve recall compared with one generic query.
SEARCH_QUERIES = {
    "Programming": ["programming fundamentals free course", "computer programming for beginners free course"],
    "Python": ["Python full course beginners", "Python programming course free"],
    "C": ["C programming full course", "C programming beginners course"],
    "C++": ["C++ full course beginners", "C++ programming course"],
    "C#": ["C# full course beginners", "C sharp programming course"],
    "Java": ["Java full course beginners", "Java programming course"],
    "JavaScript": ["JavaScript full course beginners", "JavaScript programming course"],
    "TypeScript": ["TypeScript full course", "TypeScript beginners course"],
    "Go": ["Golang full course", "Go programming beginners"],
    "Rust": ["Rust programming full course", "Rust beginners course"],
    "PHP": ["PHP full course beginners", "PHP programming course"],
    "Kotlin": ["Kotlin full course beginners", "Kotlin programming course"],
    "Swift": ["Swift programming full course", "Swift beginners course"],
    "Data Structures": ["data structures full course", "data structures and algorithms beginners"],
    "Algorithms": ["algorithms full course computer science", "algorithms for beginners course"],
    "Competitive Programming": ["competitive programming course", "competitive programming beginners"],
    "Object-Oriented Programming": ["object oriented programming full course", "OOP programming course beginners"],
    "Software Engineering": ["software engineering full course", "software engineering beginners"],
    "Design Patterns": ["design patterns full course", "software design patterns beginners"],
    "Clean Code": ["clean code course", "clean code software engineering"],
    "Software Testing": ["software testing full course", "software testing beginners"],
    "QA": ["QA testing full course", "quality assurance software testing course"],
    "Git & GitHub": ["Git GitHub full course", "GitHub for beginners course"],
    "Frontend Development": ["frontend development full course", "frontend web development beginners"],
    "HTML & CSS": ["HTML CSS full course", "HTML CSS beginners course"],
    "React": ["React full course beginners", "React JS course"],
    "Angular": ["Angular full course beginners", "Angular development course"],
    "Vue.js": ["Vue JS full course beginners", "Vue.js course"],
    "Backend Development": ["backend development full course", "backend development beginners"],
    "Node.js": ["Node.js full course beginners", "Node JS backend course"],
    "Django": ["Django full course beginners", "Django web development course"],
    "Flask": ["Flask full course beginners", "Flask Python web development course"],
    "ASP.NET": ["ASP.NET Core full course", "ASP.NET beginners course"],
    "Full Stack Development": ["full stack development full course", "full stack web development beginners"],
    "Flutter": ["Flutter full course beginners", "Flutter app development course"],
    "Android Development": ["Android development full course", "Android app development beginners"],
    "iOS Development": ["iOS development Swift full course", "iOS app development beginners"],
    "React Native": ["React Native full course", "React Native beginners course"],
    "SQL": ["SQL full course beginners", "SQL database course"],
    "Databases": ["database management full course", "databases for beginners"],
    "Data Analysis": ["data analysis full course", "data analysis beginners"],
    "Data Science": ["data science full course", "data science beginners"],
    "Business Intelligence": ["business intelligence full course", "BI beginners course"],
    "Data Engineering": ["data engineering full course", "data engineering beginners"],
    "Big Data": ["big data full course", "big data technologies beginners"],
    "Artificial Intelligence": ["artificial intelligence full course", "AI beginners course"],
    "Machine Learning": ["machine learning full course", "machine learning beginners"],
    "Deep Learning": ["deep learning full course", "deep learning beginners"],
    "Computer Vision": ["computer vision full course", "computer vision beginners"],
    "Natural Language Processing": ["NLP full course", "natural language processing beginners"],
    "Generative AI": ["generative AI full course", "generative AI beginners"],
    "Large Language Models": ["LLM full course", "large language models beginners"],
    "Reinforcement Learning": ["reinforcement learning full course", "reinforcement learning beginners"],
    "MLOps": ["MLOps full course", "MLOps beginners"],
    "Cloud Computing": ["cloud computing full course", "cloud computing beginners"],
    "AWS": ["AWS full course beginners", "AWS cloud practitioner course"],
    "Microsoft Azure": ["Azure full course beginners", "Microsoft Azure fundamentals"],
    "Google Cloud": ["Google Cloud full course beginners", "GCP beginners course"],
    "DevOps": ["DevOps full course beginners", "DevOps engineering course"],
    "Docker": ["Docker full course beginners", "Docker container course"],
    "Kubernetes": ["Kubernetes full course beginners", "Kubernetes course"],
    "Linux": ["Linux full course beginners", "Linux command line course"],
    "Computer Networks": ["computer networks full course", "networking fundamentals beginners"],
    "Operating Systems": ["operating systems full course", "operating systems beginners"],
    "System Administration": ["system administration full course", "sysadmin beginners"],
    "Cybersecurity": ["cybersecurity full course beginners", "cyber security fundamentals course"],
    "Ethical Hacking": ["ethical hacking full course", "ethical hacking beginners"],
    "Web Security": ["web security full course", "web application security beginners"],
    "Network Security": ["network security full course", "network security beginners"],
    "Digital Forensics": ["digital forensics full course", "digital forensics beginners"],
    "Embedded Systems": ["embedded systems full course", "embedded systems beginners"],
    "Internet of Things": ["IoT full course", "internet of things beginners"],
    "Robotics": ["robotics full course beginners", "robotics programming course"],
    "Game Development": ["game development full course", "game development beginners"],
    "Unity": ["Unity full course beginners", "Unity game development course"],
    "Unreal Engine": ["Unreal Engine full course", "Unreal Engine beginners"],
    "Blockchain": ["blockchain full course beginners", "blockchain development course"],
    "Web3": ["Web3 full course", "Web3 development beginners"],
    "AR VR": ["AR VR development full course", "augmented reality virtual reality beginners"],
    "UI UX": ["UI UX design full course", "UI UX beginners course"],
    "Product Management": ["product management full course", "product management beginners"],
}
